from turtle import Turtle, Screen
timmy = Turtle()
print(timmy)
timmy.shape("turtle")
timmy.color("Mediumvioletred")
timmy.pensize(4)

timmy.left(135)
timmy.forward(90)
timmy.right(25)
timmy.forward(25)
timmy.right(45)
timmy.forward(25)
timmy.right(45)
timmy.forward(25)
timmy.right(45)
timmy.forward(25)
timmy.right(20)
timmy.forward(20)
timmy.left(90)
timmy.forward(20)
timmy.right(20)
timmy.forward(25)
timmy.right(45)
timmy.forward(25)
timmy.right(45)
timmy.forward(25)
timmy.right(45)
timmy.forward(25)
timmy.right(25)
timmy.forward(90)


my_screen = Screen()
print(my_screen.canvheight)
my_screen.exitonclick()
